# 配置菜单导航的名称、路径和图标icon.
menu:
  Index:
    url: /
    icon:
  Tags:
    url: /tags
    icon:
  Categories:
    url: /categories
    icon:
  Archives:
    url: /archives
    icon:
  About:
    url: /about
    icon:
  Friends:
    url: /friends
    icon:
  Contact:
    url: /contact
    icon:

# 首页封面轮播图的相关配置.
cover:
  showPrevNext: true # 是否显示左右切换按钮.
  showIndicators: true # 是否显示指示器.
  autoLoop: true # 是否自动轮播.
  duration: 120 # 切换延迟时间.
  intervalTime: 5000 # 自动切换下一张的间隔时间.

# 配置首页显示"梦想"的语句.
dream:
  enable: true
  showTitle: true
  title: 神秘嘉宾
  text: 我搬到谁的隔壁，谁成了我的邻居。鸣谢生命有你参与，笑纳我的邀请。

# 是否在首页显示音乐.
music:
  enable: true
  showTitle: false
  title: 听听音乐
  fixed: false # 开启吸底模式
  autoplay: false # 是否自动播放
  theme: '#542674'
  loop: 'all' # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'list' # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto' # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.5 # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: false # 列表默认折叠
  listMaxHeight: '135px' #列表最大高度
  wyplaylist: '131915944' #网易云音乐歌单id
# 是否在首页显示视频.
video:
  enable: false
  showTitle: true
  title: 邓紫棋 - 差不多姑娘
  url: /medias/video/chabuduoguniang.mp4 # 必填
  pic:
  thumbnails:
  height: # 如：400
  autoplay: true # 是否自动播放
  theme: '#42b983'
  loop: true # 是否循环播放
  preload: 'auto' # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7

# 是否显示推荐文章的标题
recommend:
  showTitle: true

# 配置网站favicon和网站LOGO
favicon: /favicon.ico
logo: /medias/zyb.jpg


# 首页 banner 中的第二个按钮的配置，包括按钮的显示名称、font awesome图标和按钮的超链接.
indexbtn:
  enable: true
  name: Github
  icon: fa-github-alt
  url: https://github.com/zhangyongbo


# 首页 banner 中的第二行个人信息配置，留空即不启用
socialLink:
  qq: 785419852
  github: zhangyongbo
  weibo:
  email: china.zhangyongbo@gmail.com
  zhihu:
  wechat: zybforwx


# 是否激活文章 TOC 功能，并配置TOC支持选中哪些标题类型，这是全局配置。
# 可以在某篇文章的 Front-matter 中再加上`toc: false`，使该篇文章关闭TOC目录功能
toc:
  enable: true
  heading: h1, h2, h3, h4
  showToggleBtn: true # 是否显示切换TOC目录展开收缩的按钮

# 代码是否折行
code:
  break: false

# 是否激活文章末尾的打赏功能，默认激活（你替换为的你自己的微信、支付宝二维码图片、或者使用网络图片也可以）.
reward:
  enable: false
  title: 写作不易，客官能否打赏一杯奶茶？
  wechat: /medias/reward/wechat.jpg
  alipay: /medias/reward/alipay.jpg


# 是否激活复制文章时追加博客和作者的版权信息.
copyright:
  enable: false
  minCharNumber: 120 # 至少复制多少个字符就追加版权信息.
  description: 本文章著作权归作者所有，任何形式的转载都请注明出处。


# 是否激活mathjax数学公式，这是全局配置，但文章仍然不会都开启mathjax渲染，
# 考虑到mathjax加载比较耗时，你还需要在需要渲染的文章的Front-matter中再加上`mathjax: true`才行.
mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# 文章字数统计、阅读时长、总字数统计
# 激活前请确认你已经安装了 hexo-wordcount 插件，安装命令: `npm i --save hexo-wordcount`
wordCount:
  enable: true
  postWordCount: true
  min2read: true
  totalCount: true


# 是否激活点击页面的'爱心'效果，默认激活.
clicklove:
  enable: true

# 在”关于”页面中配置个人信息，包括头像、职业和个人介绍.
profile:
  avatar: /medias/zyb.jpg
  career: JAVA | CMS | ACTIVITI
  introduction: 一个Java方向的小码农，从事CMS、Portal、智慧政务、智能运维系统的研发工作


# 在“关于”页面配置"我的项目"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myProjects:
  enable: false
  data:
    hexo-matery-modified:
      icon: fa-meetup
      iconBackground: 'linear-gradient(to bottom right, #66BB6A 0%, #81C784 100%)'
      url: https://github.com/zhangyongbo/hexo-matery-modified
      desc: 我的个性化配置过的博客源码，即下即用。
    ConParser:
        icon: fa-database
        iconBackground: 'linear-gradient(to bottom right, #F06292 0%, #EF5350 100%)'
        url: https://github.com/godweiyang/ConParser
        desc: 基于dynet的成分句法分析模型整合。
    ECNU-BeamerTemplate:
        icon: fa-file-text-o
        iconBackground: 'linear-gradient(to bottom right, #29B6F6 0%, #1E88E5 100%)'
        url: https://github.com/godweiyang/ECNU_BeamerTemplate
        desc: 基于Latex Beamer的华东师范大学PPT模板。


# 在“关于”页面配置"我的技能"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
mySkills:
  enable: false
  data:
    Java:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 90%
    Spring、Spring MVC、Spring Boot:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 90%
    Hibernate、MyBatis:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 90%
    Activiti:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 80%
    MySQL、Oracle、SQLServer、KingBase、GBase:
      background: 'linear-gradient(to right, #4CAF50 0%, #81C784 100%)'
      percent: 80%
    HTML、JavaScript、JQuery:
      background: 'linear-gradient(to right, #FFEB3B 0%, #FFF176 100%)'
      percent: 80%
    Tomcat、WebLogic、TongWeb:
      background: 'linear-gradient(to right, #FFEB3B 0%, #FFF176 100%)'
      percent: 80%


# 在“关于”页面配置"我的相册"图片，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myGallery:
  enable: false
  data:
    - /medias/zyb/0.jpg
    - /medias/zyb/1.jpg
    - /medias/zyb/2.jpg


# 设置在归档页面中是否显示'文章日历'控件
postCalendar: true


# Gitalk 评论模块的配置，默认为不激活
gitalk:
  enable: true
  owner: zhangyongbo
  repo: gitalk
  oauth:
    clientId: 968642bc6faa447e79d0
    clientSecret: cbbda9af6a5ab1a49a053eab50aa6be46a418da4
  admin: zhangyongbo


# Gitment 评论模块的配置，默认为不激活
gitment:
  enable: false
  owner:
  repo:
  oauth:
    clientId:
    clientSecret:


# Disqus评论模块的配置，默认为不激活
disqus:
  enable: false
  shortname: china-zyb

# Livere 来必力评论模块的配置，默认为不激活
livere:
  enable: false
  uid:

# Valine 评论模块的配置，默认为不激活，如要使用，就请激活该配置项，并设置 appId 和 appKey.
valine:
  enable: false
  appId:
  appKey:
  notify: false
  verify: false
  visitor: true
  avatar: 'mm' # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  pageSize: 10
  placeholder: 'just go go' # Comment Box placeholder


# 配置是否在 header 中显示 fork me on github 的图标，默认为true，你可以修改为你的仓库地址.
githubLink:
  enable: true
  url: https://github.com/zhangyongbo
  title: Fork Me


# 阅读文章的密码验证功能，如要使用此功能请激活该配置项，并在对应文章的Front-matter中写上'password'的键和加密后的密文即可.
# 请注意：为了保证密码原文不会被泄露到网页中，文章的密码必须是通过'SHA256'加密的，这样就不会被破解.
verifyPassword:
  enable: false
  promptMessage: 请输入访问本文章的密码
  errorMessage: 密码错误，将返回主页！

# 不蒜子(http://busuanzi.ibruce.info/) 网站统计
busuanziStatistics:
  enable: false
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: true # 总人次


# 添加 Google Analytics 配置
googleAnalytics:
  enable: true
  id:


# 使用到的前端库，可按需替换成对应的CDN地址，如果下面未指定具体的版本号，使用最新的版本即可.
libs:
  css:
    fontAwesome: /libs/awesome/css/font-awesome.min.css # V4.7.0
    materialize: /libs/materialize/materialize.min.css # 1.0.0
    aos: /libs/aos/aos.css
    animate: /libs/animate/animate.min.css # V3.5.1
    lightgallery: /libs/lightGallery/css/lightgallery.min.css # V1.6.11
    aplayer: /libs/aplayer/APlayer.min.css
    dplayer: /libs/dplayer/DPlayer.min.css
    gitalk: /libs/gitalk/gitalk.css
    jqcloud: /libs/jqcloud/jqcloud.css
    tocbot: /libs/tocbot/tocbot.css
  js:
    jquery: /libs/jquery/jquery-2.2.0.min.js
    materialize: /libs/materialize/materialize.min.js # 1.0.0
    masonry: /libs/masonry/masonry.pkgd.min.js # v4.0.0
    aos: /libs/aos/aos.js
    scrollProgress: /libs/scrollprogress/scrollProgress.min.js
    lightgallery: /libs/lightGallery/js/lightgallery-all.min.js # V1.6.11
    clicklove: /libs/others/clicklove.js
    busuanzi: /libs/others/busuanzi.pure.mini.js
    aplayer: /libs/aplayer/APlayer.min.js
    dplayer: /libs/dplayer/DPlayer.min.js
    crypto: /libs/cryptojs/crypto-js.min.js
    echarts: /libs/echarts/echarts.min.js
    gitalk: /libs/gitalk/gitalk.min.js
    jqcloud: /libs/jqcloud/jqcloud-1.0.4.min.js
    tocbot: /libs/tocbot/tocbot.min.js
    md5: /libs/others/md5.min.js


# 无文章特色图片时需要显示的文章特色图片.
featureImages:
- /medias/featureimages/0.jpg
- /medias/featureimages/1.jpg
- /medias/featureimages/2.jpg
- /medias/featureimages/3.jpg
- /medias/featureimages/4.jpg
- /medias/featureimages/5.jpg
- /medias/featureimages/6.jpg
- /medias/featureimages/7.jpg
- /medias/featureimages/8.jpg
- /medias/featureimages/9.jpg
- /medias/featureimages/10.jpg
- /medias/featureimages/11.jpg
- /medias/featureimages/12.jpg
- /medias/featureimages/13.jpg
- /medias/featureimages/14.jpg
- /medias/featureimages/15.jpg
- /medias/featureimages/16.jpg
- /medias/featureimages/17.jpg
- /medias/featureimages/18.jpg
- /medias/featureimages/19.jpg
- /medias/featureimages/20.jpg
- /medias/featureimages/21.jpg
- /medias/featureimages/22.jpg
- /medias/featureimages/23.jpg
- /medias/featureimages/24.jpg
- /medias/featureimages/25.jpg
- /medias/featureimages/26.jpg
- /medias/featureimages/27.jpg
- /medias/featureimages/28.jpg
- /medias/featureimages/29.jpg
- /medias/featureimages/30.jpg
- /medias/featureimages/32.jpg
- /medias/featureimages/33.jpg
- /medias/featureimages/34.jpg
- /medias/featureimages/35.jpg
- /medias/featureimages/36.jpg
- /medias/featureimages/37.jpg
- /medias/featureimages/38.jpg
- /medias/featureimages/39.jpg
- /medias/featureimages/40.jpg
- /medias/featureimages/41.jpg
- /medias/featureimages/42.jpg
- /medias/featureimages/43.jpg
- /medias/featureimages/44.jpg
- /medias/featureimages/45.jpg
- /medias/featureimages/46.jpg
- /medias/featureimages/47.jpg
- /medias/featureimages/48.jpg
- /medias/featureimages/49.jpg
- /medias/featureimages/50.jpg
- /medias/featureimages/51.jpg
- /medias/featureimages/52.jpg
- /medias/featureimages/53.jpg
- /medias/featureimages/54.jpg
- /medias/featureimages/55.jpg
- /medias/featureimages/56.jpg
- /medias/featureimages/57.jpg
- /medias/featureimages/58.jpg
- /medias/featureimages/59.jpg
- /medias/featureimages/60.jpg
- /medias/featureimages/61.jpg
- /medias/featureimages/62.jpg
- /medias/featureimages/63.jpg
- /medias/featureimages/64.jpg
- /medias/featureimages/65.jpg
- /medias/featureimages/67.jpg
- /medias/featureimages/68.jpg
- /medias/featureimages/69.jpg
- /medias/featureimages/70.jpg
- /medias/featureimages/71.jpg
- /medias/featureimages/72.jpg
- /medias/featureimages/73.jpg
- /medias/featureimages/74.jpg
- /medias/featureimages/75.jpg
- /medias/featureimages/76.jpg
- /medias/featureimages/77.jpg
- /medias/featureimages/78.jpg
- /medias/featureimages/79.jpg
- /medias/featureimages/80.jpg
- /medias/featureimages/81.jpg
- /medias/featureimages/82.jpg
- /medias/featureimages/83.jpg
- /medias/featureimages/84.jpg
- /medias/featureimages/85.jpg
- /medias/featureimages/86.jpg
- /medias/featureimages/87.jpg
- /medias/featureimages/88.jpg
- /medias/featureimages/89.jpg
- /medias/featureimages/90.jpg
- /medias/featureimages/91.jpg
- /medias/featureimages/92.jpg
- /medias/featureimages/93.jpg
- /medias/featureimages/94.jpg
- /medias/featureimages/95.jpg
- /medias/featureimages/96.jpg
- /medias/featureimages/97.jpg
- /medias/featureimages/98.jpg
- /medias/featureimages/99.jpg
- /medias/featureimages/100.jpg
- /medias/featureimages/101.jpg
- /medias/featureimages/102.jpg
- /medias/featureimages/103.jpg
- /medias/featureimages/104.jpg
- /medias/featureimages/105.jpg
- /medias/featureimages/106.jpg
- /medias/featureimages/107.jpg
- /medias/featureimages/108.jpg
- /medias/featureimages/109.jpg
- /medias/featureimages/110.jpg
- /medias/featureimages/111.jpg
- /medias/featureimages/112.jpg
- /medias/featureimages/113.jpg


  # default 配置文章的默认转载规则


  # 您可以使用在文章md文件的 front-matter 中指定 reprintPolicy 来给单个文章配置转载规则

  # 可用的转载规则有：
  # 这些转载规则的意义请参考：https://creativecommons.org/choose/?lang=zh
  # cc_by  知识共享署名 4.0 国际许可协议
  # cc_by_nd  知识共享署名-禁止演绎 4.0 国际许可协议
  # cc_by_sa  知识共享署名-相同方式共享 4.0 国际许可协议
  # cc_by_nc  知识共享署名-非商业性使用 4.0 国际许可协议
  # cc_by_nc_nd  知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议
  # cc_by_nc_sa  知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议
  # cc0  CC0 1.0 通用 (CC0 1.0) 公共领域贡献 ） https://creativecommons.org/publicdomain/zero/1.0/deed.zh

  # noreprint  不允许转载
  # pay  付费转载
reprint:
  enable: false # 是否启用“转载规则限定模块”
  default: cc_by
